import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { AuthenticationProvider } from "../context/Authentication";

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Movies4wiz | Home",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthenticationProvider>
      <body className={inter.className}>
        <header className="sticky top-0 select-none">
          <Navbar />
        </header>
        <main className="select-none">{children}</main>
        <footer className="select-none">
          <Footer />
        </footer>
      </body>
      </AuthenticationProvider>
    </html>
  )
}
